[changelog]
header = ""

body = """
{% if version -%}
## {{ version | replace(from="rust-v", to="") | trim_start_matches(pat="v") }} - {{ timestamp | date(format="%Y-%m-%d") }}
{%- else %}
## [unreleased]
{% endif %}

{%- for group, commits in commits | group_by(attribute="group") %}
### {{ group | striptags | trim }}

{% for commit in commits %}- {% if commit.scope %}*({{ commit.scope }})* {% endif %}{% if commit.breaking %}[**breaking**] {% endif %}{{ commit.message | upper_first }}
{% endfor %}

{%- endfor -%}
"""

footer = ""

trim = true
postprocessors = []

[git]
conventional_commits = true
tag_pattern = "^rust-v.*$"

commit_parsers = [
  { message = "^feat",    group = "<!-- 0 -->ğŸš€ Features" },
  { message = "^fix",     group = "<!-- 1 -->ğŸª² Bug Fixes" },
  { message = "^docs",    group = "<!-- 2 -->ğŸ“š Docs" },
  { message = "^refactor",group = "<!-- 3 -->â™»ï¸ Refactor" },
  { message = "^perf",    group = "<!-- 4 -->âš¡ Performance" },
  { message = "^test",    group = "<!-- 5 -->ğŸ§ª Tests" },
  { message = "^ci",      group = "<!-- 7 -->ğŸ”§ CI" },
  { message = "^bump",    group = "<!-- 6 -->ğŸ›³ï¸ Release" },
  { message = ".*",       group = "<!-- 10 -->ğŸ’¼ Other" },
]

filter_unconventional = false
sort_commits = "oldest"
topo_order = false
